import { Button, StandardButton, VerticalBox } from "std-widgets.slint";

export component InstallerWindow inherits Dialog {
    VerticalBox {
        Text {
            horizontal-alignment: center;
            text: "SimpleSteamWrapper not installed in Steam.";
        }
        Text {
            horizontal-alignment: center;
            text: "Do you want to add it as a compatibility tool ?";
        }
    }

    StandardButton{
        accessible-role: AccessibleRole.button;
        kind: yes;
    }

    StandardButton {
        accessible-role: AccessibleRole.button;
        kind: no;
    }
}
