import { ComboBox, CheckBox, VerticalBox, HorizontalBox, SpinBox, Button } from "std-widgets.slint";

export global AppConf  {
    pure callback get_opt(string) -> string;
    callback set_opt(string, string);

    public pure function get_opt_bool(path: string) -> bool {
        return get_opt(path) == "true";
    }

    public function set_opt_bool(path: string, parameter: bool) {
        set_opt(path, parameter ? "true" : "false");
    }

    public pure function get_opt_int(path: string) -> int {
        return get_opt(path).to-float();
    }

    public function set_opt_int(path: string, parameter: int) {
        set_opt(path, parameter.to-fixed(0));
    }

    public pure function get_opt_float(path: string) -> float {
        return get_opt(path).to-float();
    }

    public function set_opt_float(path: string, parameter: float) {
        set_opt(path, parameter.to-fixed(2));
    }
}

export component MainGUI inherits Window {
    width: 500px;
    height: 600px;
    title: "Simple Steam Wrapper";

    in-out property <int> selected_compat_tool_index;
    in property <[string]> compat_tools;

    in-out property <int> selected_gpu_index;
    in property <[string]> gpus;

    in-out property <bool> editing_defaults;
    callback reset_to_defaults();
    
    callback update_wrapper();

    pure callback get_combobox_gpu_id(int) -> string;

    in property <string> game_app_id: "";

    in property <bool> reload: false;
    callback force_reload();

    if(!reload): VerticalBox {
        padding: 10px;
        alignment: start;

        Text { text: "Choose runner (Use ProtonUpQt to add more)"; }

        ComboBox {
            model: root.compat_tools;
            current-index <=> selected_compat_tool_index;
            selected(current-value) => { AppConf.set_opt("compat_tool", current-value) }
        }

        select_gpu_check := CheckBox {
            text: "Select Vulkan GPU (Using multiple env vars)";
            checked: AppConf.get_opt_bool("enabled_tweaks.select_gpu");
            toggled => { AppConf.set_opt_bool("enabled_tweaks.select_gpu", self.checked); }
        }

        ComboBox {
            model: root.gpus;
            enabled: select_gpu_check.checked;
            current-index <=> selected_gpu_index;
            selected(current-value) => { AppConf.set_opt("selected_gpu", get_combobox_gpu_id(self.current-index)) }
        }

        CheckBox {
            text: "Use NVAPI extensions (PROTON_USE_NVAPI)";
            checked: AppConf.get_opt_bool("enabled_tweaks.proton_nvapi");
            toggled => { AppConf.set_opt_bool("enabled_tweaks.proton_nvapi", self.checked); }
        }
        CheckBox {
            text: "Feral's Gamemode";
            checked: AppConf.get_opt_bool("enabled_tweaks.gamemode");
            toggled => { AppConf.set_opt_bool("enabled_tweaks.gamemode", self.checked); }
        }
        gamescope_check := CheckBox {
            text: "Use Gamescope";
            checked: AppConf.get_opt_bool("enabled_tweaks.gamescope");
            toggled => { AppConf.set_opt_bool("enabled_tweaks.gamescope", self.checked); }
        }
        if gamescope_check.checked: Rectangle {
            border-width: 1px;
            border-radius: 10px;
            border-color: darkgrey;

            VerticalBox {
                spacing: 0;
                HorizontalBox {
                    ComboBox {
                        model: ["Fullscreen", "Windowed"];
                        current-index: AppConf.get_opt_bool("gamescope_settings.fullscreen") ? 0 : 1;
                        selected(current-value) => { AppConf.set_opt_bool("gamescope_settings.fullscreen", self.current-index == 0) }
                    }
                    CheckBox {
                        text: "Force Grab Cursor";
                        checked: AppConf.get_opt_bool("gamescope_settings.force_grab_cursor");
                        toggled => { AppConf.set_opt_bool("gamescope_settings.force_grab_cursor", self.checked) }
                    }
                }
                HorizontalBox {
                    VerticalBox {
                        property <int> forced_width: AppConf.get_opt_int("gamescope_settings.forced_width");

                        w_checkbox := CheckBox {
                            text: "Width";
                            checked: forced_width > 0;
                            toggled => {
                                forced_width = (self.checked) ? 720 : -1;
                                AppConf.set_opt_int("gamescope_settings.forced_width", (self.checked) ? 720 : -1);
                            }
                        }
                        SpinBox {
                            enabled: w_checkbox.checked;
                            maximum: 9999;
                            value: forced_width > -1 ? forced_width : 0;
                            edited(value) => { AppConf.set_opt_int("gamescope_settings.forced_width", value) }
                        }
                    }
                    VerticalBox {
                        property <int> forced_height: AppConf.get_opt_int("gamescope_settings.forced_height");

                        h_checkbox := CheckBox {
                            text: "Height";
                            checked: forced_height > 0;
                            toggled => {
                                forced_height = (self.checked) ? 720 : -1;
                                AppConf.set_opt_int("gamescope_settings.forced_height", (self.checked) ? 720 : -1);
                            }
                        }
                        SpinBox {
                            enabled: h_checkbox.checked;
                            maximum: 9999;
                            value: forced_height > -1 ? forced_height : 0;
                            edited(value) => { AppConf.set_opt_int("gamescope_settings.forced_height", value) }
                        }
                    }
                    VerticalBox {
                        property <int> framerate: AppConf.get_opt_int("gamescope_settings.framerate");

                        framerate_check := CheckBox {
                            text: "Framerate";
                            checked: framerate > 0;
                            toggled => {
                                framerate = (self.checked) ? 60 : -1;
                                AppConf.set_opt_int("gamescope_settings.framerate", (self.checked) ? 60 : -1);
                            }
                        }
                        SpinBox {
                            enabled: framerate_check.checked;
                            maximum: 1000;
                            value: framerate > -1 ? framerate : 0;
                            edited(value) => { AppConf.set_opt_int("gamescope_settings.framerate", value) }
                        }
                    }
                }
            }
        }

        CheckBox {
            text: "Use MangoHUD";
            checked: AppConf.get_opt_bool("enabled_tweaks.mangohud");
            toggled => { AppConf.set_opt_bool("enabled_tweaks.mangohud", self.checked); }
        }

        dxvk_hud_mode := CheckBox {
            text: "DXVK Hud Mode";
            checked: AppConf.get_opt_bool("enabled_tweaks.dxvk_hud_mode");
            toggled => { AppConf.set_opt_bool("enabled_tweaks.dxvk_hud_mode", self.checked); }
        }
        if(dxvk_hud_mode.checked): ComboBox {
            model: ["compiler","devinfo","fps","full","memory","gpuload","drawcalls","frametimes"];
            current-value: AppConf.get_opt("dxvk_hud_settings.mode");
            selected(current-value) => { AppConf.set_opt("dxvk_hud_settings.mode", current-value) }
        }

        HorizontalBox {
            if (!game_app_id.is-empty): HorizontalBox {
                Text {
                    font-weight: 600;
                    text: "AppId: " + game_app_id;
                }
                CheckBox {
                    text: "Show defaults";
                    checked <=> editing-defaults;
                    toggled => { force_reload(); }
                }
            }
            Button {
                text: "Default";
                clicked => { reset_to_defaults(); }
            }
            Button {
                text: "Update Wrapper";
                clicked => { update_wrapper(); }
            }
        }
    }
}
