run-name: Publish

on:
  workflow_dispatch:
    inputs:
      semver:
        type: choice
        description: Choose the semver
        options:
          - "Patch - Backward compatible bug fixes"
          - "Minor - Adding functionality in a backward compatible manner"
          - "Major - Incompatible API changes"

env:
  APP_NAME: "Simple-Steam-Wrapper"
  SEMVER_UPDATE: "${{ inputs.semver }}"

jobs:
  build:
    runs-on: skydust-runner
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    
    container:
      image: "public.ecr.aws/docker/library/rust:1.96.0-slim-trixie"

    env:
      RUST_MIN_STACK: 16777216
    steps:
      - name: Prepare runner deps
        run: |
          apt update
          apt install -y --no-install-recommends nodejs git bash npm curl jq
          npm config set @skydust:registry=https://gitea.skydust.fr/api/packages/skydust/npm/
          npm install -g @skydust/toolkit@latest

      - name: Prepare build deps
        run: |
          apt install -y --no-install-recommends docker-cli build-essential perl clang libssl-dev cmake make curl pkg-config libfontconfig-dev libx11-dev
          echo "CC=clang" >> $GITEA_ENV
          echo "CXX=clang++" >> $GITEA_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Getting version
        uses: https://gitea.skydust.fr/actions/get-version@v1

      - name: Update rust package version
        run: |
          log_info "Updating Cargo.toml version to $(yellow)$NEW_VERSION"
          sed -Ei "s|^(version = \")[^\"]*|\1${NEW_VERSION}|" Cargo.toml
          cat Cargo.toml

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Archive binary
        run: |
          OUT_DIR=release/${{ matrix.target }}
          mkdir -p $OUT_DIR
          cp target/${{ matrix.target }}/release/${APP_NAME} $OUT_DIR/${APP_NAME}-${{ matrix.target }}
          
      - name: Upload artifact
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: release
          path: "release"
          retention-days: 1

  release:
    name: Validate release
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: skydust-runner
    steps:
      - name: Release
        uses: https://gitea.skydust.fr/actions/create-release@v1
        with:
          semver: ${{ inputs.semver }}
          token: ${{ secrets.CI_TOKEN }}

  publish:
    name: Publishing package
    needs: release
    runs-on: skydust-runner
    steps:
      - name: Download artifact
        uses: christopherhx/gitea-download-artifact@v4
        with:
          name: release
          path: "release"

      - name: Getting version
        uses: https://gitea.skydust.fr/actions/get-version@v1

      - name: Create Release
        uses: https://gitea.com/actions/gitea-release-action@v1
        with:
          files: release/**/*
          name: "v${{ env.NEW_VERSION }}"
          token: ${{ secrets.GITEA_SERVER_URL }}
