import { ComboBox, CheckBox, VerticalBox, HorizontalBox, SpinBox, Button, ScrollView, ListView, LineEdit } from "std-widgets.slint";

export component PrefixSettingsGUI inherits Window {
    width: 500px;
    height: 300px;
    title: "Simple Steam Wrapper - Prefix";

    in property <string> game_app_id: "0";

    in property <string> prefix_path: "///";

    in property <string> runner_name: "";

    in-out property <bool> recreating_prefix: false;
    in-out property <bool> running_winetricks: false;

    callback recreate_prefix();
    callback run_winetricks();
    callback run_in_prefix(bool);

    VerticalBox {
        Text {
            text: "AppId: " + game_app_id;
        }
        Text {
            wrap: char-wrap;
            text: "Prefix: " + prefix_path;
        }
        Text {
            text: "Current runner: " + runner_name;
        }
        ScrollView {
            viewport-width: self.width;
            VerticalBox {
                HorizontalBox {
                    Button {
                        enabled: !recreating_prefix;
                        vertical-stretch: 0;
                        text: "Recreate Prefix";
                        clicked => {
                            recreating_prefix = true;
                            recreate_prefix()
                        }
                    }
                }
                HorizontalBox {
                    Button {
                        enabled: !running_winetricks;
                        vertical-stretch: 0;
                        text: "Winetricks";
                        clicked => {
                            running_winetricks = true;
                            run_winetricks()
                        }
                    }
                }
                HorizontalBox {
                    Button {
                        horizontal-stretch: 1;
                        text: "Run in game prefix";
                        clicked => { run_in_prefix(in_terminal.checked) }
                    }
                    in_terminal := CheckBox {
                        text: "In terminal";
                    }
                }
            }
        }
    }
}
