import { ComboBox, CheckBox, VerticalBox, HorizontalBox, SpinBox, Button, ScrollView, ListView, LineEdit, ProgressIndicator } from "std-widgets.slint";

// TODO: If auto-update on, check corresponding update on startup and add a 'last-update' to not spam the check
// TODO: On DLManager open, fetch corresponding GEProton and proton-cachyos versions
// TODO: Versions that are already installed in steam need to simply be "Installed"
export component DlManagerGUI inherits Window {
    width: 700px;
    height: 500px;
    title: "Simple Steam Wrapper - Download Manager";

    in property <[string]> dl_compat_tools;
    callback fetch_release(string);

    in-out property <[{ already_downloaded: bool, can_be_updated: bool, display_name: string, name: string }]> releases: [];
    in property <{ is_downloading: bool, row_id: int, percent: int }> download_state: {
        is_downloading: false,
        percent: 0
    };
    callback install_compat_tool(int);
    callback delete_compat_tool(int);
    callback update_ui_releases();

    VerticalBox {
        HorizontalBox {
            selected_list := ComboBox {
                model: dl_compat_tools;
                selected(current-value) => { fetch_release(selected_list.current-value); }
            }
            Button {
                text: "🗘";
                clicked => { fetch_release(selected_list.current-value); }
            }
        }
        ScrollView {
            VerticalBox {
                alignment: LayoutAlignment.start;
                for row[idx] in releases: Rectangle {
                    border-color: darkgrey;
                    border-width: 1px;
                    border-radius: 3px;
                    VerticalBox {
                        alignment: LayoutAlignment.start;
                        HorizontalLayout {
                            padding: 0;
                            Text {
                                vertical-alignment: center;
                                text: row.display-name;
                            }
                            VerticalLayout {
                                horizontal-stretch: 0;
                                spacing: 5px;
                                HorizontalLayout {
                                    horizontal-stretch: 0;
                                    spacing: 5px;
                                    if row.already_downloaded: Button {
                                        max-width: self.preferred-width;
                                        text: "🗑";
                                        clicked => { delete_compat_tool(idx) }
                                    }
                                    Button {
                                        max-width: self.preferred-width;
                                        text: row.can_be_updated ? "Update" : "Install";
                                        clicked => { install_compat_tool(idx) }
                                        enabled: (!download_state.is_downloading && !row.already_downloaded);
                                    }
                                }
                                //if row.can_be_updated: CheckBox {
                                //    horizontal-stretch: 0;
                                //    text: "Auto-update";
                                //}
                            }
                        }
                        if (download_state.is_downloading && idx == download_state.row-id): HorizontalBox {
                           alignment: stretch;

                           VerticalLayout {
                               alignment: center;
                               ProgressIndicator {
                                   height: 2px;
                                   progress: download_state.percent/100;
                               }
                           }

                           Text {
                               text: download_state.percent + "%";
                           }
                       }
                    }
                }
            }
        }
    }
}
