import { ComboBox, CheckBox, VerticalBox, HorizontalBox, SpinBox, Button, ScrollView, ListView, LineEdit, ProgressIndicator } from "std-widgets.slint";

// TODO: If auto-update on, check corresponding update on startup and add a 'last-update' to not spam the check
// TODO: On DLManager open, fetch corresponding GEProton and proton-cachyos versions

struct Release {
    already_downloaded: bool,
    can_be_updated: bool,
    display_name: string,
    name: string
}

struct DownloadState {
    is_downloading: bool,
    row_id: int,
    percent: int
}

export component DlManagerGUI inherits Window {
    width: 700px;
    height: 500px;
    title: "Simple Steam Wrapper - Download Manager";

    in property <[string]> provider_names;
    in property <[string]> variants;
    out property <int> current-variant-idx;
    callback fetch_release(provider_idx: int, variant_idx: int, update_variants: bool, force_refresh: bool);

    in-out property <[Release]> releases: [];
    in property <DownloadState> download_state: {
        is_downloading: false,
        percent: 0
    };
    callback install_compat_tool(int);
    callback delete_compat_tool(int);
    callback update_ui_releases();

    VerticalBox {
        HorizontalBox {
            selected_list := ComboBox {
                model: provider_names;
                selected(current-value) => {
                    fetch_release(selected_list.current-index, 0, true, false);
                }
            }
            if (variants.length > 1): variant := ComboBox {
                model: variants;
                horizontal-stretch: 0;
                current-index <=> current-variant-idx;
                selected(current-value) => { fetch_release(selected_list.current-index, self.current-index, false, false); }
            }
            Button {
                text: "🗘";
                clicked => { fetch_release(selected_list.current-index, current-variant-idx, false, true); }
            }
        }
        ScrollView {
            VerticalBox {
                alignment: LayoutAlignment.start;
                for row[idx] in releases: Rectangle {
                    border-color: darkgrey;
                    border-width: 1px;
                    border-radius: 3px;
                    VerticalBox {
                        alignment: LayoutAlignment.start;
                        HorizontalLayout {
                            padding: 0;
                            Text {
                                vertical-alignment: center;
                                text: row.display-name;
                            }
                            VerticalLayout {
                                horizontal-stretch: 0;
                                spacing: 5px;
                                HorizontalLayout {
                                    horizontal-stretch: 0;
                                    spacing: 5px;
                                    if row.already_downloaded: Button {
                                        max-width: self.preferred-width;
                                        text: "🗑";
                                        clicked => { delete_compat_tool(idx) }
                                    }
                                    Button {
                                        max-width: self.preferred-width;
                                        text: row.can_be_updated ? "Update" : "Install";
                                        clicked => { install_compat_tool(idx) }
                                        enabled: (!download_state.is_downloading && !row.already_downloaded);
                                    }
                                }
                                //if row.can_be_updated: CheckBox {
                                //    horizontal-stretch: 0;
                                //    text: "Auto-update";
                                //}
                            }
                        }
                        if (download_state.is_downloading && idx == download_state.row-id): HorizontalBox {
                           alignment: stretch;

                           VerticalLayout {
                               alignment: center;
                               ProgressIndicator {
                                   height: 2px;
                                   progress: download_state.percent/100;
                               }
                           }

                           Text {
                               text: download_state.percent + "%";
                           }
                       }
                    }
                }
            }
        }
    }
}
