import { ComboBox, CheckBox, VerticalBox, HorizontalBox, SpinBox, Button, ScrollView, ListView, LineEdit } from "std-widgets.slint";
import { AppConf } from "globals/app_conf.slint";
import { GamescopeEdit } from "widgets/gamescope_edit.slint";
import { EnvVarsEditor } from "widgets/env_vars_editor.slint";
import { HardRefresh } from "globals/hard_refresh.slint";
import { EnvVarsSettings } from "globals/env_vars_settings.slint";

export enum GUIGPUVendor {
    nvidia,
    others
}

export component MainGUI inherits Window {
    width: 575px;
    height: 600px;
    title: "Simple Steam Wrapper";

    in-out property <int> selected_compat_tool_index;
    in property <[string]> compat_tools;

    in-out property <int> selected_gpu_index;
    in-out property <GUIGPUVendor> current_gpu_vendor;
    in property <[string]> gpus;
    callback on_gpu_update(idx: int);

    in property <string> game_app_id: "0";

    in-out property <int> selected_runtime;
    in property <[string]> runtimes;

    pure callback show_download_runner();
    pure callback show_prefix_options();

    in property <string> app_version: "9.99.99";
    callback reset_to_defaults();
    callback update_wrapper();
    callback save_and_continue();

    in property <string> setting_key: AppConf.get_global_opt("general.gui_trigger_key");
    in-out property <bool> is_setting_key;
    callback enable_setting_key();

    if(HardRefresh.refresh): VerticalBox {
        ScrollView {
            viewport-width: self.width;
            VerticalBox {
                alignment: start;

                Text { text: "Choose runner"; }

                HorizontalBox {
                    ComboBox {
                        model: root.compat_tools;
                        current-index <=> selected_compat_tool_index;
                        selected(current-value) => { AppConf.set_opt_str("compat_tool", current-value) }
                    }
                    Button {
                        text: "↓";
                        clicked => { show_download_runner(); }
                    }
                }

                HorizontalLayout {
                    spacing: 10px;
                    Text {
                        vertical-alignment: center;
                        text: "Runtime (Choose sniper if unsure)";
                     }
                    ComboBox {
                        model: root.runtimes;
                        current-index <=> selected_runtime;
                        selected(current-value) => { AppConf.set_opt_str("runtime", current-value) }
                    }
                }

                if root.gpus.length > 1: HorizontalLayout {
                    spacing: 10px;
                    select_gpu_check := CheckBox {
                        text: "Select GPU";
                        checked: AppConf.get_opt_bool("enabled_tweaks.gpu_tools");
                        toggled => { AppConf.set_opt_bool("enabled_tweaks.gpu_tools", self.checked); }
                    }

                    ComboBox {
                        model: root.gpus;
                        enabled: select_gpu_check.checked;
                        current-index <=> selected_gpu_index;
                        selected(current-value) => { on_gpu_update(self.current-index); }
                    }
                }

                if current_gpu_vendor == GUIGPUVendor.nvidia: VerticalBox {
                    alignment: start;
                    padding: 0;
                    CheckBox {
                        text: "Nvidia VRAM Workaround (Apply env vars to limit freezes)";
                        checked: AppConf.get_opt_bool("enabled_tweaks.nvidia_vram_workarounds");
                        toggled => { AppConf.set_opt_bool("enabled_tweaks.nvidia_vram_workarounds", self.checked); }
                    }
                    HorizontalLayout {
                        nvapi := CheckBox {
                            text: "Use NVAPI extensions";
                            checked: AppConf.get_opt_bool("enabled_tweaks.proton_nvapi");
                            toggled => {
                                if (!self.checked) {
                                    AppConf.set_opt_bool("enabled_tweaks.proton_nvapi_vkreflex", self.checked);
                                }
                                AppConf.set_opt_bool("enabled_tweaks.proton_nvapi", self.checked);
                            }
                        }
                        if (nvapi.checked): CheckBox {
                            text: "VKReflex";
                            checked: AppConf.get_opt_bool("enabled_tweaks.proton_nvapi_vkreflex");
                            toggled => { AppConf.set_opt_bool("enabled_tweaks.proton_nvapi_vkreflex", self.checked); }
                        }
                    }
                }

                CheckBox {
                    text: "Feral's Gamemode";
                    checked: AppConf.get_opt_bool("enabled_tweaks.gamemode");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.gamemode", self.checked); }
                }

                HorizontalLayout {
                    proton_wayland := CheckBox {
                        text: "Enable wayland support (GE-Proton/proton-cachyos)";
                        checked: AppConf.get_opt_bool("enabled_tweaks.proton_wayland");
                        toggled => {
                            AppConf.set_opt_bool("enabled_tweaks.proton_wayland", self.checked);
                            if (!self.checked) {
                                AppConf.set_opt_bool("enabled_tweaks.proton_wayland_hdr", false);
                            }
                        }
                    }
                    if proton_wayland.checked: CheckBox {
                        text: "Enable HDR";
                        checked: AppConf.get_opt_bool("enabled_tweaks.proton_wayland_hdr");
                        toggled => { AppConf.set_opt_bool("enabled_tweaks.proton_wayland_hdr", self.checked); }
                    }
                }

                gamescope_check := CheckBox {
                    text: "Use Gamescope";
                    checked: AppConf.get_opt_bool("enabled_tweaks.gamescope");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.gamescope", self.checked); }
                }

                if gamescope_check.checked: GamescopeEdit {}

                CheckBox {
                    text: "Use MangoHUD";
                    checked: AppConf.get_opt_bool("enabled_tweaks.mangohud");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.mangohud", self.checked); }
                }

                HorizontalLayout {
                    spacing: 10px;
                    dxvk_hud_mode := CheckBox {
                        text: "DXVK Hud Mode";
                        checked: AppConf.get_opt_bool("enabled_tweaks.dxvk_hud_mode");
                        toggled => { AppConf.set_opt_bool("enabled_tweaks.dxvk_hud_mode", self.checked); }
                    }

                    if(dxvk_hud_mode.checked): ComboBox {
                        model: ["compiler","devinfo","fps","full","memory","gpuload","drawcalls","frametimes"];
                        current-value: AppConf.get_opt_str("dxvk_hud_settings.mode");
                        selected(current-value) => { AppConf.set_opt_str("dxvk_hud_settings.mode", current-value) }
                    }
                }

                custom_env_vars := CheckBox {
                    text: "Custom env vars";
                    checked: AppConf.get_opt_bool("enabled_tweaks.custom_env_vars");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.custom_env_vars", self.checked); }
                }

                if(custom_env_vars.checked): EnvVarsEditor {}
            }
        }
        VerticalBox {
            if (!game_app_id.is-empty): HorizontalBox {
                Text {
                    vertical-alignment: center;
                    font-weight: 600;
                    text: "AppId: " + game_app_id;
                }
                CheckBox {
                    text: "Show defaults";
                    checked: AppConf.editing_defaults;
                    toggled => {
                        EnvVarsSettings.save_env_vars();
                        AppConf.update_global_config();
                        AppConf.editing_defaults = self.checked;
                        HardRefresh.force_refresh();
                    }
                }
                Button {
                    text: "Show prefix options";
                    clicked => { show_prefix_options() }
                }
            }
            HorizontalBox {
                Button {
                    text: "Reset";
                    clicked => { reset_to_defaults(); }
                }
                Button {
                    horizontal-stretch: 0;
                    text: is_setting_key ? "Press a key" : setting_key;
                    clicked => {
                        is_setting_key = true;
                        enable_setting_key();
                    }
                }
                Button {
                    text: "Update Wrapper";
                    clicked => { update_wrapper(); }
                }
                Button {
                    text: "Save and " + (game_app_id.is-empty ? "quit" : "continue");
                    clicked => { save_and_continue(); }
                }
            }
            Rectangle {
                CheckBox {
                    x: 0;
                    text: "Show on game crash";
                    checked: AppConf.get_global_opt("general.show_on_game_crash") == "true";
                    toggled => {
                        AppConf.set_global_opt("general.show_on_game_crash", self.checked ? "true" : "false")
                    }
                }
                Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: "Version: "+ app_version;
                }
            }
        }
    }
}
