import { ComboBox, CheckBox, VerticalBox, HorizontalBox, SpinBox, Button, ScrollView, ListView, LineEdit } from "std-widgets.slint";
import { AppConf } from "app_conf.slint";
import { GamescopeEdit } from "widgets/gamescope_edit.slint";
import { EnvVarsEditor } from "widgets/env_vars_editor.slint";

export component MainGUI inherits Window {
    width: 500px;
    height: 600px;
    title: "Simple Steam Wrapper";

    in-out property <int> selected_compat_tool_index;
    in property <[string]> compat_tools;

    in-out property <int> selected_gpu_index;
    in-out property <string> current_gpu_vendor;
    in property <[string]> gpus;
    callback on_gpu_update();
    pure callback get_combobox_gpu_id(int) -> string;

    in-out property <[{ key: string, value: string }]> env_vars: [];
    callback remove_env_var(int);
    callback add_env_var();
    callback save_custom_values();

    in property <string> game_app_id: "";
    in-out property <bool> editing_defaults;

    pure callback show_download_runner();
    pure callback show_prefix_options();

    in property <string> app_version;
    callback reset_to_defaults();
    callback update_wrapper();

    in property <bool> reload: false;
    callback force_reload();

    if(!reload): VerticalBox {
        ScrollView {
            viewport-width: self.width;
            VerticalBox {
                alignment: start;

                Text { text: "Choose runner"; }

                HorizontalBox {
                    ComboBox {
                        model: root.compat_tools;
                        current-index <=> selected_compat_tool_index;
                        selected(current-value) => { AppConf.set_opt("compat_tool", current-value) }
                    }
                    Button {
                        text: "↓";
                        clicked => { show_download_runner(); }
                    }
                }

                if root.gpus.length > 1: Rectangle {
                    select_gpu_check := CheckBox {
                        text: "Select GPU";
                        checked: AppConf.get_opt_bool("enabled_tweaks.gpu_tools");
                        toggled => { AppConf.set_opt_bool("enabled_tweaks.gpu_tools", self.checked); }
                    }

                    ComboBox {
                        model: root.gpus;
                        enabled: select_gpu_check.checked;
                        current-index <=> selected_gpu_index;
                        selected(current-value) => {
                            AppConf.set_opt("selected_gpu", get_combobox_gpu_id(self.current-index));
                            on_gpu_update();
                        }
                    }
                }

                if current_gpu_vendor == "nvidia": HorizontalLayout {
                    nvapi := CheckBox {
                        text: "Use NVAPI extensions";
                        checked: AppConf.get_opt_bool("enabled_tweaks.proton_nvapi");
                        toggled => {
                            if (!self.checked) {
                                AppConf.set_opt_bool("enabled_tweaks.proton_nvapi_vkreflex", self.checked);
                            }
                            AppConf.set_opt_bool("enabled_tweaks.proton_nvapi", self.checked);
                        }
                    }
                    if (nvapi.checked): CheckBox {
                        text: "VKReflex";
                        checked: AppConf.get_opt_bool("enabled_tweaks.proton_nvapi_vkreflex");
                        toggled => { AppConf.set_opt_bool("enabled_tweaks.proton_nvapi_vkreflex", self.checked); }
                    }
                }

                CheckBox {
                    text: "Feral's Gamemode";
                    checked: AppConf.get_opt_bool("enabled_tweaks.gamemode");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.gamemode", self.checked); }
                }
                CheckBox {
                    text: "Enable wayland support (GE-Proton/proton-cachyos)";
                    checked: AppConf.get_opt_bool("enabled_tweaks.proton_wayland");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.proton_wayland", self.checked); }
                }

                gamescope_check := CheckBox {
                    text: "Use Gamescope";
                    checked: AppConf.get_opt_bool("enabled_tweaks.gamescope");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.gamescope", self.checked); }
                }

                if gamescope_check.checked: GamescopeEdit {}

                CheckBox {
                    text: "Use MangoHUD";
                    checked: AppConf.get_opt_bool("enabled_tweaks.mangohud");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.mangohud", self.checked); }
                }

                dxvk_hud_mode := CheckBox {
                    text: "DXVK Hud Mode";
                    checked: AppConf.get_opt_bool("enabled_tweaks.dxvk_hud_mode");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.dxvk_hud_mode", self.checked); }
                }

                if(dxvk_hud_mode.checked): ComboBox {
                    model: ["compiler","devinfo","fps","full","memory","gpuload","drawcalls","frametimes"];
                    current-value: AppConf.get_opt("dxvk_hud_settings.mode");
                    selected(current-value) => { AppConf.set_opt("dxvk_hud_settings.mode", current-value) }
                }

                custom_env_vars := CheckBox {
                    text: "Custom env vars";
                    checked: AppConf.get_opt_bool("enabled_tweaks.custom_env_vars");
                    toggled => { AppConf.set_opt_bool("enabled_tweaks.custom_env_vars", self.checked); }
                }

                if(custom_env_vars.checked): EnvVarsEditor {
                    current_env_vars <=> env_vars;
                    remove_env_var(idx) => { remove_env_var(idx) }
                    add_env_var => { add_env_var() }
                }
            }
        }
        VerticalBox {
            if (!game_app_id.is-empty): HorizontalBox {
                Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    font-weight: 600;
                    text: "AppId: " + game_app_id;
                }
                CheckBox {
                    text: "Show defaults";
                    checked <=> editing_defaults;
                    toggled => {
                        editing_defaults = !editing_defaults;
                        save_custom_values();
                        editing_defaults = !editing_defaults;
                        force_reload();
                    }
                }
                Button {
                    text: "Show prefix options";
                    clicked => { show_prefix_options() }
                }
            }
            HorizontalBox {
                Button {
                    text: "Default";
                    clicked => { reset_to_defaults(); }
                }
                Button {
                    text: "Update Wrapper";
                    clicked => { update_wrapper(); }
                }
                Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: "Version: "+ app_version;
                }
            }
        }
    }
}
